name: context
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  context:
    runs-on: ubuntu-20.04
    steps:
    - name: Dump Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "${GITHUB_CONTEXT}"
