name: mac stuff
on:
  pull_request:

jobs:
  context-10:
    runs-on: macos-10.15
    steps:
      - name: Sysctl
        run: |
          sysctl kern.osproductversion

  context-11:
    runs-on: macos-11
    steps:
      - name: Sysctl
        run: |
          sysctl kern.osproductversion

  context-12:
    runs-on: macos-12
    steps:
      - name: Sysctl
        run: |
          sysctl kern.osproductversion
