name: continue-on-error
on:
  workflow_dispatch:
  pull_request:

jobs:
  continue-on-error:
    runs-on: ubuntu-20.04
    steps:
    - name: Test continue-on-error
      continue-on-error: true
      run: exit 1
