name: context
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  pull_request:

jobs:
  context:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: ["macOS", "linux"]
        python: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2
    - name: GitHub matrix
      run: |
        echo "${{ toJSON(matrix) }}"
    - name: Dump Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "${GITHUB_CONTEXT}"
        git rev-parse HEAD
    - name: Test null
      if: ${{ github.lololololo == null }}
      run: |
        echo "that is very null"
    - name: Test non null
      if: ${{ github.action != null }}
      run: |
        echo "very much non null"
