# When a package is published (or updated), do some sort of quality check on it
---
name: expression_test
on:
  workflow_dispatch:
  pull_request:

jobs:
  expression_test:
    runs-on: ubuntu-20.04
    steps:
      # we never get here and that is a bug!
      - name: Dump Value
        env:
          GITHUB_EVENT: ${{ github.event_name || 'raw_string' }}
        run: echo "${GITHUB_EVENT}"

