name: booleans
on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  IS_PULL_OR_DISPATCH: |
    ${{ toJSON(github.event_name == 'workflow_dispatch' || 
    github.event_name == 'pull_request') }}
  IS_PULL: ${{ github.event_name == 'pull_request' }}
  IS_NOT_PULL: ${{ github.event_name != 'pull_request' }}

jobs:
  booleans:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump env
        run: |
          echo ${IS_PULL_OR_DISPATCH}
          echo ${IS_PULL}
          echo "test_true=true" >> $GITHUB_ENV
          echo "test_false=false" >> $GITHUB_ENV

      - name: Run if not pull
        if: ${{ !fromJSON(env.IS_PULL) }}
        run: echo "Hello there!"

      - name: Run if test_true
        if: ${{ fromJSON(env.test_true) }}
        run: |
          echo ${test_true}
          echo ${test_false}

      - name: Run if not test_false
        if: ${{ !fromJSON(env.test_false) }}
        run: |
          echo ${test_true}
          echo ${test_false}
