# When a package is published (or updated), do some sort of quality check on it
---
name: json_test
on:
  workflow_dispatch:

jobs:
  json_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Successful step
        run: |
          echo "Success"
      # we never get here and that is a bug!
      - name: Dump Value
        env:
          WORKFLOW_SUCCESSFUL: ${{ job.status }}
        run: echo "${WORKFLOW_SUCCESSFUL}"

