# When a package is published (or updated), do some sort of quality check on it
---
name: qualify
on:
  registry_package:
    types:
      - published
      - updated

jobs:
  qualify:
    runs-on: ubuntu-latest
    steps:
      # we never get here and that is a bug!
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"
