# When a package is published (or updated), do some sort of quality check on it
---
name: qualify
on:
  registry_package:
    types:
      - published
      - updated

jobs:
  qualify:
    runs-on: ubuntu-20.04
    steps:
      # we never get here and that is a bug!
      - name: Dump GitHub event
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "${GITHUB_EVENT}"
