# When a release is created in GitHub, make a docker image
---
name: release
on:
  release:
    types:
      - created

env:
  DOCKER_IMAGE: ghcr.io/icetdrinker/no-github-package-docker-registry-package-event

jobs:
  docker-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Pull a known image
        run: docker pull debian:buster-slim
      - name: Re-tag that image
        run: docker image tag debian:buster-slim "${DOCKER_IMAGE}:latest"
      - name: Push that image
        run: docker push "${DOCKER_IMAGE}:latest"
