name: repo_dispatch
on:
  repository_dispatch:
    types:
      - env-docker-preflight

jobs:
  repo_dispatch:
    if: ${{ github.event_name != 'repository_dispatch' || github.event.action == 'env-docker-preflight' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Successful step
        run: |
          echo "Success"
      - name: Failing step
        run: |
          exit 1
      - name: Try something
        if: ${{ always() && github.event_name == 'repository_dispatch' && github.event.action == 'env-docker-preflight' }}
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}
