name: report
on:
  workflow_dispatch:
  pull_request:

env:
  ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  reporting-test:
    runs-on: ubuntu-20.04
    outputs:
      echo-report: ${{ steps.report.outputs.echo-report || format('Something went wrong during preflight ({0})', env.ACTION_RUN_URL) }}
      printf-report: ${{ steps.report.outputs.printf-report || format('Something went wrong during preflight ({0})', env.ACTION_RUN_URL) }}
      default-value-output: ${{ steps.report.outputs.default-value-output || format('Something went wrong during preflight ({0})', env.ACTION_RUN_URL) }}
    steps:
    - name: Write report with echo
      if: ${{ always() }}
      id: report
      run: |
        ECHO_REPORT=$(echo -e "This is a well formatted report with echo.\nWith newlines.")
        PRINTF_REPORT=$(printf "This is a well formatted report with printf.\nWith newlines.")
        echo "::set-output name=echo-report::${ECHO_REPORT//$'\n'/'%0A'}"
        echo "::set-output name=printf-report::${PRINTF_REPORT//$'\n'/'%0A'}"

  collect-reports:
    needs: [reporting-test]
    runs-on: ubuntu-20.04
    steps:
    - name: Echo report
      if: ${{ always() }}
      run: |
        echo "${{ needs.reporting-test.outputs.echo-report }}"
        echo "${{ needs.reporting-test.outputs.printf-report }}"
        echo "${{ needs.reporting-test.outputs.default-value-output }}"
